// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteQuery(arg1:string):Promise<main.QueryResult>;

export function GetTableSchema(arg1:string):Promise<Array<main.ColumnInfo>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDB(arg1:string):Promise<Array<main.Table>>;
